
# 通过`python -m pytest`调用`pytest`
你可以通过python的解释器来执行测试：

    python -m pytest [...]

但是，这和直接执行`pytest [...]`命令的效果几乎是一模一样的；


# **`pytest`执行结束时返回的状态码**
`pytest`命令执行结束，可能会返回以下六种状态码：

- 0（OK）：所有收集到的用例测试通过
- 1（TESTS_FAILED）：有用例测试失败
- 2（INTERRUPTED）：用户打断测试执行
- 3（INTERNAL_ERROR）：测试执行的过程中，发生内部错误
- 4（USAGE_ERROR）：`pytest`命令使用错误
- 5（NO_TESTS_COLLECTED）：没有收集到测试用例

它们在枚举类 [_pytest.main.ExitCode](https://docs.pytest.org/en/latest/reference.html#_pytest.main.ExitCode) 中声明。并且，其作为公开API的一部分，能够直接引入和访问：

```python
from pytest import ExitCode
```


# **获取帮助信息**

    pytest --version  # 查看版本号和pytest的引入路径
    pytest -h  # 查看帮助信息


# 最多允许失败的测试用例数
当达到最大上限时，退出执行；如未配置，则没有上限：

    pytest -x  # 遇到第一个失败时，退出执行
    pytest --maxfail==2  # 遇到第二个失败时，退出执行


# **执行指定的测试用例**
`pytest`支持多种方式来执行特定的测试用例：

## 执行指定模块中的测试用例：

    pytest test_mod.py

## 执行指定目录下所有的测试用例：

    pytest testing/

## 执行文件名、类名或者函数名中包含特定关键字的测试用例：

    # 执行当前目录下，名字包含`_class`但不包含`two`的测试用例。
    pytest -k "_class and not two" .

> 注意：python的关键字不可以应用在`-k`选项中，例如，`class`、`def`等。

## 执行指定nodeid的测试用例：
`pytest`为每一个收集到的测试用例指定一个唯一的`nodeid`。其由模块名加说明符构成，中间以`::`间隔。

其中，说明符可以是**类名、函数名以及由`parametrize`标记赋予的参数**：

```python
# src/chapter-2/test_nodeid.py

import pytest


def test_one():
    print('test_one')
    assert 1


class TestNodeId:
    def test_one(self):
        print('TestNodeId::test_one')
        assert 1

    @pytest.mark.parametrize('x,y', [(1, 1), (3, 4)])
    def test_two(self, x, y):
        print(f'TestNodeId::test_two::{x} == {y}')
        assert x == y
```

在上述示例中，我们创建了三个测试用例，分别对应不同的**说明符**：

- 指定**函数名**执行

        $ pipenv run pytest -q -s src/chapter-2/test_nodeid.py::test_one
        test_one
        .
        1 passed in 0.01s

- 指定**类名+函数名**执行

        $ pipenv run pytest -q -s src/chapter-2/test_nodeid.py::TestNodeId::test_one
        TestNodeId::test_one
        .
        1 passed in 0.01s

- 指定**由`parametrize`标记赋予的参数**执行

        $ pipenv run pytest -q -s src/chapter-2/test_nodeid.py::TestNodeId::test_two[1-1]
        TestNodeId::test_two::1 == 1
        .
        1 passed in 0.01s

    这里对参数`x`、`y`赋值的形式是`[1-1]`，中间以`-`间隔；
    
    单个或多个参数的赋值形式以此类比；并且，只能为`[1-1]`或者`[3-4]`，其它的会报错；

## 执行指定标记的用例

    pytest -m slow

## 执行指定包中的测试用例

    pytest --pyargs pkg.testing

`pytest`会引入`pkg.testing`包，并在它的系统目录下搜寻测试用例并执行；


# 修改回溯信息的输出模式
pytest回溯信息的输出一共有六种模式：**auto/long/short/line/native/no**，用`--tb`选项指定：

    pytest -l, --showlocals         # 打印本地变量
    pytest --tb=auto                # 默认模式
    pytest --tb=long                # 尽可能详细的输出
    pytest --tb=short               # 更简短的输出
    pytest --tb=line                # 每个失败信息总结在一行中
    pytest --tb=native              # python的标准输出
    pytest --tb=no                  # 不打印失败信息

`--full-trace`是一种比`--tb=long`更详细的输出模式。它甚至能观察到用户打断执行（`Ctrl+C`）时的回溯信息，而上述六种模式默认是不输出此类信息的。


# 总结报告
`-r`选项可以在执行结束后，打印一个简短的总结报告。在执行的测试用例很多时，可以让你对结果有个清晰的了解：

```python
# src/chapter-2/test_report.py

import pytest


@pytest.fixture
def error_fixture():
    assert 0


def test_ok():
    print("ok")


def test_fail():
    assert 0


def test_error(error_fixture):
    pass


def test_skip():
    pytest.skip("skipping this test")


def test_xfail():
    pytest.xfail("xfailing this test")


@pytest.mark.xfail(reason="always xfail")
def test_xpass():
    pass
```

    $ pipenv run pytest -q -rA src/chapter-2/test_report.py 
    .FEsxX                                                            [100%]
    ================================ ERRORS =================================
    _____________________ ERROR at setup of test_error ______________________

        @pytest.fixture
        def error_fixture():
    >       assert 0
    E       assert 0

    src/chapter-2/test_report.py:27: AssertionError
    =============================== FAILURES ================================
    _______________________________ test_fail _______________________________

        def test_fail():
    >       assert 0
    E       assert 0

    src/chapter-2/test_report.py:35: AssertionError
    ================================ PASSES =================================
    ________________________________ test_ok ________________________________
    ------------------------- Captured stdout call --------------------------
    ok
    ======================== short test summary info ========================
    PASSED src/chapter-2/test_report.py::test_ok
    SKIPPED [1] /Users/yaomeng/Private/Projects/pytest-chinese-doc/src/chapter-2/test_report.py:44: skipping this test
    XFAIL src/chapter-2/test_report.py::test_xfail
      reason: xfailing this test
    XPASS src/chapter-2/test_report.py::test_xpass always xfail
    ERROR src/chapter-2/test_report.py::test_error - assert 0
    FAILED src/chapter-2/test_report.py::test_fail - assert 0
    1 failed, 1 passed, 1 skipped, 1 xfailed, 1 xpassed, 1 error in 0.08s

`-r`选项后面要紧接这一个参数，用于过滤显示测试用例的结果。

以下是所有有效的字符参数：

- f：失败的
- E：出错的
- s：跳过执行的
- x：跳过执行，并标记为xfailed的
- X：跳过执行，并标记为xpassed的
- p：测试通过的
- P：测试通过，并且有输出信息的；即用例中有`print`等
- a：除了测试通过的，其他所有的；即除了`p`和`P`的
- A：所有的

上述字符参数可以叠加使用，例如：我们期望过滤出失败的和未执行的：

    pytest -rfs


# **失败时加载[PDB](https://docs.python.org/3/library/pdb.html)(Python Debugger)环境**
`PDB`是`python`内建的诊断器，`pytest`允许通过以下命令在执行失败时进入这个诊断器模式：

    pytest --pdb

`pytest`会在测试用例失败（或者`Ctrl+C`）时，调用这个诊断器：

```python
# src/chapter-2/test_pdb.py

def test_fail():
    x = 1
    assert x == 0
```

    $ pipenv run pytest -q --pdb src/chapter-2/test_pdb.py 
    F
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

        def test_fail():
            x = 1
    >       assert x == 0
    E       assert 1 == 0

    src/chapter-2/test_pdb.py:25: AssertionError
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    >>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>
    > /Users/yaomeng/Private/Projects/pytest-chinese-doc/src/chapter-2/test_pdb.py(25)test_fail()
    -> assert x == 0
    (Pdb) 
    (Pdb) x
    1
    (Pdb) 
    (Pdb) import sys
    (Pdb) sys.last_value
    AssertionError('assert 1 == 0')
    (Pdb) sys.last_type
    <class 'AssertionError'>
    (Pdb) sys.last_traceback
    <traceback object at 0x1077ec808>

你还可以访问测试用例的本地变量`x`；

失败的信息存储在`sys.last_value, sys.last_type, sys.last_traceback`变量中，你可以在交互环境中访问它们；

使用`exit`命令，退出`PDB`环境；


# 开始执行时就加载PDB环境
通过以下命令，`pytest`允许你在每个测试用例开始执行时，就加载`PDB`环境：

    pytest --trace


# **设置断点**
在测试用例代码中添加`import pdb;pdb.set_trace()`，当其被调用时，`pytest`会停止这条用例的输出：

- 其他用例不受影响；
- 通过`continue`命令，退出`PDB`环境，并继续执行用例；


# **使用内置的中断函数**
python 3.7介绍了一个内置`breakpoint()`函数。pytest可以在以下场景中支持使用：

- 当`breakpoint()`被调用，并且`PYTHONBREAKPOINT`为`None`时，`pytest`会使用内部自定义的`PDB`代替系统的；
- 测试执行结束时，自动切回系统自带的`PDB`；
- 当加上`--pdb`选项时，`breakpoint()`和测试发生错误时，都会调用内部自定义的`PDB`；
- `--pdbcls`选项允许指定一个用户自定义的`PDB`类；


# **分析测试执行时间**
获取执行最慢的10个测试用例：

    pytest --durations=10

默认情况下，`pytest`不会显示执行时间<0.01s的测试用例，可以使用`-vv`选项查看它们；


# 错误句柄
> 5.0版本新增特性

在测试执行中发生段错误或者超时的情况下，`faulthandler`标准模块可以转储`python`的回溯信息；

它在`pytest`的执行中默认使能，使用`-p no:faulthandler`选项可以关闭它；

同样，`faulthandler_timeout=X`配置项，可用于当测试用例的完成时间超过`X`秒时，转储所有线程的`python`回溯信息：

```ini
# src/chapter-2/pytest.ini

[pytest]
faulthandler_timeout=5
```
配置测试执行的超时时间是5秒；

```python
# test_fault_handler.py 

import time


def test_faulthandler():
    time.sleep(7)
    assert 1
```
测试用例中添加等待7秒的操作；

- 默认使能`faulthandler`的情况：

        $ pipenv run pytest -q src/chapter-2/test_faulthandler.py 
        Timeout (0:00:05)!
        Thread 0x000000010ff275c0 (most recent call first):
          File "/Users/yaomeng/Private/Projects/pytest-chinese-doc/src/chapter-2/test_faulthandler.py", line 26 in test_faulthandler
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/python.py", line 170 in pytest_pyfunc_call
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/python.py", line 1423 in runtest
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/runner.py", line 117 in pytest_runtest_call
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/runner.py", line 192 in <lambda>
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/runner.py", line 220 in from_call
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/runner.py", line 192 in call_runtest_hook
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/runner.py", line 167 in call_and_report
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/runner.py", line 87 in runtestprotocol
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/runner.py", line 72 in pytest_runtest_protocol
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/main.py", line 256 in pytest_runtestloop
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/main.py", line 235 in _main
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/main.py", line 191 in wrap_session
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/main.py", line 228 in pytest_cmdline_main
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/lib/python3.7/site-packages/_pytest/config/__init__.py", line 77 in main
          File "/Users/yaomeng/.local/share/virtualenvs/pytest-chinese-doc-EK3zIUmM/bin/pytest", line 10 in <module>
        .                                                                 [100%]
        1 passed in 7.02s

    在执行刚超过5秒的时候会打印出回溯信息。但不会中断测试的执行；

- 去使能`faulthandler`的情况：

        $ pipenv run pytest -q -p no:faulthandler src/chapter-2/test_faulthandler.py 
        .                                                                 [100%]
        1 passed in 7.02s

    超时并不会触发回溯信息的打印；

> 注意：
> 
> 这个功能是从[pytest-faulthandler](https://github.com/pytest-dev/pytest-faulthandler)插件合并而来的，但是有两点不同：
> 
> - 去使能时，使用`-p no:faulthandler`代替原来的`--no-faulthandler`;
> - 使用`faulthandler_timeout `配置项代替`--faulthandler-timeout`命令行选项来配置超时时间。当然，你也可以使用`-o faulthandler_timeout=X`在命令行配置；
